### ISSUE TITLE
SweetJS Syntax Definitions

### ISSUE THREAD

**Issue by ostera** [ostera/zazen#17]
Having a set of SweetJS syntax definitions bundled in this repo (but exposed as a separate package: `zazen.syntax`) will let us write ridiculously concise and elegant code.

Ideas below.

#### Slim Arrow for an Arrow function.

No more `Arrow( (x) => { } )`. Same semantics as `=>`, but automatic construction of the Arrow object.

Limited to ` x -> { body }` or `(a,b) -> { body }` functions. This further prevents mistakenly lifting a uncurried function over several arguments into an arrow (which would make the rest of the arguments always undefined).

```js
a = x -> x
b = (a, b) -> a+b
```

#### Operators!

```js
a *** b === a.product(b)
a +++ b === a.sum(b)
a >>> b === a.pipe(b)
a <<< b === a.compose(b)
```

Just some ideas, day dreaming a bit today.

**Comment by xaviervia** [comment]
You might’ve seen https://github.com/ion-lang/ion

**Comment by leostera** [comment]
Closed in favor of writing a superset language.
