### ISSUE TITLE
SumTypes

### ISSUE THREAD

**Issue by ostera** [ostera/zazen#36]
Given that every Type we create with `type :: name -> Type` currently is self-aware, creating variadic `sumType` type constructor could work to bring in nice things like checking if something is either Left _or_ Right in runtime.

Stab:

```js
const sumType = (...types) => ( typeNames => ({
  "@@type": typeNames,
  is: x => typesNames.indexOf( x["@@type"] ) !== -1,
}) )(types.map( t => t["@@type"] ))
```

**Comment by leostera** [comment]
This approach has been deprecated in favor of several _constructors_ for the same data type.

Example:

```hs
data Either a b = Left a | Right b
```

Here both `Left a` and `Right b` are of type `Either`. They are just different constructors for the same type.
