### ISSUE TITLE
Monorepo

### ISSUE THREAD

**Issue by ostera** [ostera/zazen#37]
We are spanning a few things here that could easily be encapsulated in their own modules:

* `zazen.arrow`, the Arrow class implementation
* `zazen.prelude`, all the basic functions, Either, Maybe, the Type creators, matchers, annotations
* `incrementals`, the Cell, runCell, and incrementally computed Graph -- can't remember when I got the [package name](https://www.npmjs.com/package/incrementals) 🥇

**Comment by leostera** [comment]
Addressed by #44
